"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var sidebars = {
    tutorialSidebar: [
        // 시작하기 페이지를 맨 위에 배치
        'intro',
        // Freshservice - IT 서비스 관리
        {
            type: 'category',
            label: '🔧 Freshservice (ITSM)',
            collapsed: false,
            items: [
                {
                    type: 'category',
                    label: '🧪 PoC 가이드',
                    collapsed: true,
                    items: [
                        'freshservice/poc-guides/guide',
                    ],
                },
                {
                    type: 'category',
                    label: '📚시작하기',
                    collapsed: true,
                    items: [
                        {
                            type: 'category',
                            label: '👥 사용자 관리',
                            collapsed: true,
                            items: [
                                'freshservice/getting-started/user-management/agents',
                                'freshservice/getting-started/user-management/roles-permissions',
                                'freshservice/getting-started/user-management/requesters',
                                'freshservice/getting-started/user-management/import-csv',
                                'freshservice/getting-started/user-management/agent-id',
                                'freshservice/getting-started/user-management/custom-fields',
                                'freshservice/getting-started/user-management/csv-guidelines',
                                'freshservice/getting-started/user-management/merge-requesters',
                                'freshservice/getting-started/user-management/password-policy',
                                'freshservice/getting-started/user-management/change-password',
                                'freshservice/getting-started/user-management/department-fields',
                                'freshservice/getting-started/user-management/export-agents',
                                'freshservice/getting-started/user-management/import-agents',
                                'freshservice/getting-started/user-management/auto-associate',
                                'freshservice/getting-started/user-management/group-members',
                                'freshservice/getting-started/user-management/agent-groups',
                                'freshservice/getting-started/user-management/requester-groups',
                                'freshservice/getting-started/user-management/manage-requesters',
                                'freshservice/getting-started/user-management/import-departments',
                                'freshservice/getting-started/user-management/merge-advanced',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🌐 셀프 서비스 포털',
                            collapsed: true,
                            items: [
                                'freshservice/getting-started/self-service-portal-introduction/branding',
                                'freshservice/getting-started/self-service-portal-introduction/vanity-url',
                                'freshservice/getting-started/self-service-portal-introduction/access-login',
                                'freshservice/getting-started/self-service-portal-introduction/ssl-cert',
                                'freshservice/getting-started/self-service-portal-introduction/chatbot',
                            ],
                        },
                        {
                            type: 'category',
                            label: '⚙️ 시스템 설정',
                            collapsed: true,
                            items: [
                                'freshservice/getting-started/setting-up-freshservice/onboarding',
                                'freshservice/getting-started/setting-up-freshservice/requirements',
                                'freshservice/getting-started/setting-up-freshservice/mailbox',
                                'freshservice/getting-started/setting-up-freshservice/agents',
                                'freshservice/getting-started/setting-up-freshservice/asset-scan',
                                'freshservice/getting-started/setting-up-freshservice/timezones',
                                'freshservice/getting-started/setting-up-freshservice/languages',
                                'freshservice/getting-started/setting-up-freshservice/catalog',
                                'freshservice/getting-started/setting-up-freshservice/sla-policy',
                            ],
                        },
                        {
                            type: 'category',
                            label: '📝 폼 및 템플릿',
                            collapsed: true,
                            items: [
                                'freshservice/getting-started/form-fields-and-form-templates/understanding-different-types-ticket-fields',
                                'freshservice/getting-started/form-fields-and-form-templates/setting-up-form-fields-tickets-problems-changes-releases',
                                'freshservice/getting-started/form-fields-and-form-templates/creating-custom-fields-ticket-problem-change-release-task-form',
                                'freshservice/getting-started/form-fields-and-form-templates/understanding-dependent-fields',
                                'freshservice/getting-started/form-fields-and-form-templates/using-dependent-fields-tickets-problems-changes-releases',
                                'freshservice/getting-started/form-fields-and-form-templates/setting-up-dropdown-fields',
                                'freshservice/getting-started/form-fields-and-form-templates/setting-up-multi-select-dropdown',
                                'freshservice/getting-started/form-fields-and-form-templates/setting-up-rich-text-sections-content-fields',
                                'freshservice/getting-started/form-fields-and-form-templates/dynamic-sections',
                                'freshservice/getting-started/form-fields-and-form-templates/archive-delete-custom-ticket-field',
                                'freshservice/getting-started/form-fields-and-form-templates/creating-ticket-change-template',
                                'freshservice/getting-started/form-fields-and-form-templates/create-no-code-dynamic-forms-business-rules',
                                'freshservice/getting-started/form-fields-and-form-templates/create-no-code-dynamic-change-forms-business-rules',
                                'freshservice/getting-started/form-fields-and-form-templates/business-rules-usecases',
                                'freshservice/getting-started/form-fields-and-form-templates/business-rules-troubleshooting-guide',
                                'freshservice/getting-started/form-fields-and-form-templates/customizing-service-desk-statuses',
                            ],
                        },
                    ],
                },
                {
                    type: 'category',
                    label: '👨‍💼 관리자 가이드',
                    collapsed: true,
                    items: [
                        {
                            type: 'category',
                            label: '⚙️ 관리자 설정',
                            collapsed: true,
                            items: [
                                'freshservice/user-guide-admin/admin-settings/index',
                                'freshservice/user-guide-admin/admin-settings/general-settings',
                                'freshservice/user-guide-admin/admin-settings/user-management',
                                'freshservice/user-guide-admin/admin-settings/service-desk-productivity',
                                'freshservice/user-guide-admin/admin-settings/reorganization-renaming-admin',
                                'freshservice/user-guide-admin/admin-settings/asset-management',
                                'freshservice/user-guide-admin/admin-settings/export-service-desk-data',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🎯 시작하기',
                            collapsed: true,
                            items: [
                                'freshservice/user-guide-admin/getting-started/index',
                            ],
                        },
                        {
                            type: 'category',
                            label: '📊 CMDB',
                            collapsed: true,
                            items: [
                                'freshservice/user-guide-admin/cmdb/index',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🚀 릴리스 관리',
                            collapsed: true,
                            items: [
                                'freshservice/user-guide-admin/release-management/index',
                            ],
                        },
                        {
                            type: 'category',
                            label: '💡 솔루션 (지식 베이스)',
                            collapsed: true,
                            items: [
                                'freshservice/user-guide-admin/solutions/index',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🔄 변경 관리',
                            collapsed: true,
                            items: [
                                'freshservice/user-guide-admin/change-management/index',
                            ],
                        },
                        {
                            type: 'category',
                            label: '📋 인시던트 관리',
                            collapsed: true,
                            items: [
                                'freshservice/user-guide-admin/incident-management/index',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🔍 문제 관리',
                            collapsed: true,
                            items: [
                                'freshservice/user-guide-admin/problem-management/index',
                            ],
                        },
                        {
                            type: 'category',
                            label: '📈 보고서',
                            collapsed: true,
                            items: [
                                'freshservice/user-guide-admin/reports/index',
                            ],
                        },
                    ],
                },
                {
                    type: 'category',
                    label: '📘 IT 서비스 관리 지원 가이드',
                    collapsed: true,
                    items: [
                        {
                            type: 'category',
                            label: '🎫 티켓 시작하기',
                            collapsed: true,
                            items: [
                                'freshservice/itsm/getting-started-with-tickets/viewing-accessing-ticket-information',
                                'freshservice/itsm/getting-started-with-tickets/understanding-ticket-views',
                                'freshservice/itsm/getting-started-with-tickets/filtering-tickets-using-views',
                                'freshservice/itsm/getting-started-with-tickets/kanban-board-tickets-service-requests',
                                'freshservice/itsm/getting-started-with-tickets/managing-ticket-properties',
                                'freshservice/itsm/getting-started-with-tickets/understanding-custom-ticket-statuses',
                                'freshservice/itsm/getting-started-with-tickets/merging-tickets-together',
                                'freshservice/itsm/getting-started-with-tickets/logging-walk-in-requests',
                                'freshservice/itsm/getting-started-with-tickets/creating-canned-responses',
                                'freshservice/itsm/getting-started-with-tickets/using-dynamic-placeholders-canned-responses',
                                'freshservice/itsm/getting-started-with-tickets/freddy-response-suggestions',
                                'freshservice/itsm/getting-started-with-tickets/inserting-kbase-article-suggested-solutions',
                                'freshservice/itsm/getting-started-with-tickets/private-notes-internal-sharing',
                                'freshservice/itsm/getting-started-with-tickets/non-invasive-updates-public-notes',
                                'freshservice/itsm/getting-started-with-tickets/detecting-agent-collision-tickets',
                                'freshservice/itsm/getting-started-with-tickets/increase-agent-productivity-custom-dashboards',
                                'freshservice/itsm/getting-started-with-tickets/enhancements-ticket-list-view',
                                'freshservice/itsm/getting-started-with-tickets/ticket-table-view-refresh-changes',
                                'freshservice/itsm/getting-started-with-tickets/real-time-sync-enhanced-auto-refresh',
                                'freshservice/itsm/getting-started-with-tickets/refreshing-header-global-navigations',
                                'freshservice/itsm/getting-started-with-tickets/viewing-percentage-change-trends-widgets',
                                'freshservice/itsm/getting-started-with-tickets/missing-tickets-troubleshooting-guide',
                                'freshservice/itsm/getting-started-with-tickets/discontinuation-canned-response-suggester',
                            ],
                        },
                        {
                            type: 'category',
                            label: '📋 인시던트 관리',
                            collapsed: true,
                            items: [
                                'freshservice/itsm/incident-management/understanding-sla-policies',
                                'freshservice/itsm/incident-management/defining-default-sla-policy',
                                'freshservice/itsm/incident-management/creating-multiple-sla-policies-departments-groups',
                                'freshservice/itsm/incident-management/setting-default-business-hours',
                                'freshservice/itsm/incident-management/configuring-multiple-business-hours',
                                'freshservice/itsm/incident-management/priority-matrix',
                                'freshservice/itsm/incident-management/managing-ticket-escalations',
                                'freshservice/itsm/incident-management/configuring-feedback-options',
                                'freshservice/itsm/incident-management/customizing-ticket-fields-field-manager',
                                'freshservice/itsm/incident-management/setting-up-support-email-address',
                                'freshservice/itsm/incident-management/creating-spf-record',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🔄 변경 관리',
                            collapsed: true,
                            items: [
                                'freshservice/itsm/change-management/getting-started-changes',
                                'freshservice/itsm/change-management/understanding-change-phases',
                                'freshservice/itsm/change-management/planning-work-phases-tasks',
                                'freshservice/itsm/change-management/creating-change-types',
                                'freshservice/itsm/change-management/creating-change-workflows',
                                'freshservice/itsm/change-management/change-planning-templates',
                                'freshservice/itsm/change-management/change-request-from-change-agent',
                                'freshservice/itsm/change-management/change-enablement',
                                'freshservice/itsm/change-management/change-advisory-board',
                                'freshservice/itsm/change-management/agents-change-management-roles',
                                'freshservice/itsm/change-management/setting-up-ola-policies-tasks',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🎯 티켓 액션',
                            collapsed: true,
                            items: [
                                'freshservice/itsm/ticket-actions/adding-time-entries-tickets-problems-changes',
                                'freshservice/itsm/ticket-actions/adding-custom-fields-time-entries',
                                'freshservice/itsm/ticket-actions/viewing-ticket-activity-history',
                                'freshservice/itsm/ticket-actions/adding-child-tickets-ticket-freshservice',
                                'freshservice/itsm/ticket-actions/adding-child-tickets-incidents-freshservice',
                                'freshservice/itsm/ticket-actions/linking-incidents-existing-new-problems',
                                'freshservice/itsm/ticket-actions/linking-incidents-existing-new-changes',
                                'freshservice/itsm/ticket-actions/share-ticket-with-agents',
                                'freshservice/itsm/ticket-actions/share-ticket-with-requesters',
                                'freshservice/itsm/ticket-actions/forwarding-tickets-third-party',
                                'freshservice/itsm/ticket-actions/monitoring-important-tickets-becoming-watcher',
                                'freshservice/itsm/ticket-actions/using-canned-responses-ticket-replies',
                                'freshservice/itsm/ticket-actions/adding-existing-solution-response-ticket',
                                'freshservice/itsm/ticket-actions/creating-satisfaction-surveys-service-desk',
                                'freshservice/itsm/ticket-actions/enabling-ticket-closure-rules-incidents-service-requests',
                                'freshservice/itsm/ticket-actions/using-keyboard-shortcuts-service-desk',
                                'freshservice/itsm/ticket-actions/performing-actions-tickets-email-commands',
                                'freshservice/itsm/ticket-actions/exporting-tickets',
                                'freshservice/itsm/ticket-actions/ticket-archival',
                                'freshservice/itsm/ticket-actions/emails-not-converted-tickets-freshservice',
                                'freshservice/itsm/ticket-actions/deflect-email-queries-email-bot',
                                'freshservice/itsm/ticket-actions/discontinuation-team-huddle',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🤖 티켓 자동화',
                            collapsed: true,
                            items: [
                                'freshservice/itsm/ticket-automations/creating-supervisor-rules',
                                'freshservice/itsm/ticket-automations/supervisor-rules-configuration-custom-ticket-status',
                                'freshservice/itsm/ticket-automations/creating-new-scenario-automation',
                                'freshservice/itsm/ticket-automations/executing-scenario-automation-tickets',
                                'freshservice/itsm/ticket-automations/schedule-recurring-tickets-scheduler',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🤖 Freddy AI 에이전트',
                            collapsed: true,
                            items: [
                                'freshservice/itsm/freddy-ai-agent/setting-up-freddy-ai-agent-slack',
                                'freshservice/itsm/freddy-ai-agent/setting-up-freddy-ai-agent-microsoft-teams',
                                'freshservice/itsm/freddy-ai-agent/bring-better-ticket-context-collaboration-tools',
                                'freshservice/itsm/freddy-ai-agent/freshservice-ms-teams-integration-faqs',
                                'freshservice/itsm/freddy-ai-agent/launching-microsoft-teams-update-servicebot-upgraded-apis',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🧠 Freddy AI 코파일럿',
                            collapsed: true,
                            items: [
                                'freshservice/itsm/freddy-ai-copilot/empower-it-staff-unlock-productivity-freddy-copilot',
                                'freshservice/itsm/freddy-ai-copilot/freddy-generate-reply-suggestions-tickets',
                                'freshservice/itsm/freddy-ai-copilot/automatic-generation-ticket-summary',
                                'freshservice/itsm/freddy-ai-copilot/perform-quick-service-desk-actions-freddy',
                                'freshservice/itsm/freddy-ai-copilot/create-help-articles-self-service-freddy-ai',
                            ],
                        },
                    ],
                },
                {
                    type: 'category',
                    label: '🏗️ IT 자산 관리 (ITAM)',
                    collapsed: true,
                    items: [
                        {
                            type: 'category',
                            label: '🚀 자산 관리 시작하기',
                            collapsed: true,
                            items: [
                                'freshservice/itam/get-started-with-assets/index',
                                'freshservice/itam/get-started-with-assets/different-types-assets-configuration-items',
                                'freshservice/itam/get-started-with-assets/adding-depreciation-assets',
                                'freshservice/itam/get-started-with-assets/adding-new-asset-configuration-item',
                                'freshservice/itam/get-started-with-assets/importing-assets',
                                'freshservice/itam/get-started-with-assets/viewing-information-configuration-items',
                                'freshservice/itam/get-started-with-assets/updating-assets-bulk',
                                'freshservice/itam/get-started-with-assets/customizing-columns-assets-list',
                                'freshservice/itam/get-started-with-assets/understanding-different-asset-states',
                                'freshservice/itam/get-started-with-assets/assigning-assets-users-departments',
                                'freshservice/itam/get-started-with-assets/mobile-app-barcode-qr-scanning',
                                'freshservice/itam/get-started-with-assets/asset-impact-incident-evaluation',
                                'freshservice/itam/get-started-with-assets/printing-barcode-labels-assets',
                                'freshservice/itam/get-started-with-assets/creation-incidents-changes-asset',
                                'freshservice/itam/get-started-with-assets/adding-importing-asset-locations',
                                'freshservice/itam/get-started-with-assets/asset-assignment-history',
                                'freshservice/itam/get-started-with-assets/asset-activity-reporting',
                                'freshservice/itam/get-started-with-assets/limitations-asset-field-types',
                                'freshservice/itam/get-started-with-assets/conditional-asset-type-fields-analytics',
                                'freshservice/itam/get-started-with-assets/new-mapping-changes-fs-d42',
                                'freshservice/itam/get-started-with-assets/cloud-compute-asset-types-deprecation',
                                'freshservice/itam/get-started-with-assets/basic-advanced-itam-switching-impacts',
                            ],
                        },
                    ],
                },
                {
                    type: 'category',
                    label: '❓ FAQ',
                    collapsed: true,
                    items: [
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/agents-and-groups/index',
                            label: '에이전트 및 그룹',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/analytics-faqs/index',
                            label: '분석 및 리포트',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/announcements/index',
                            label: '공지사항',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/api-webhooks/index',
                            label: 'API & Webhooks',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/asset-management/index',
                            label: '자산 관리',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/automations-triggers/index',
                            label: '자동화 및 트리거',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/business-hours-slas/index',
                            label: '업무 시간 및 SLA',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/changes/index',
                            label: '변경 관리',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/email/index',
                            label: '이메일',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/email-notifications/index',
                            label: '이메일 알림',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/feedback-widget/index',
                            label: '피드백 위젯',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/incidents-service-requests/index',
                            label: '인시던트 및 서비스 요청',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/new-gen-project-mgmt/index',
                            label: 'New-Gen 프로젝트 관리',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/orchestration/index',
                            label: '오케스트레이션',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/pricing-faq/index',
                            label: '가격 정책',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/priority-matrix/index',
                            label: '우선순위 매트릭스',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/problems/index',
                            label: '문제 관리',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/release/index',
                            label: '릴리스 관리',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/reports/index',
                            label: '보고서',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/sandbox/index',
                            label: '샌드박스',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/service-catalog/index',
                            label: '서비스 카탈로그',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/service-desk-faq/index',
                            label: '서비스 데스크 FAQ',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/sso/index',
                            label: 'SSO 및 인증',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/tasks/index',
                            label: '작업 관리',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/ticketing-workflow/index',
                            label: '티켓팅 워크플로우',
                        },
                        {
                            type: 'doc',
                            id: 'freshservice/faqs/workspaces/index',
                            label: '워크스페이스',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: '🔧 플랫폼',
                    collapsed: true,
                    items: [
                        'freshservice/platform/platform-components-overview',
                        'freshservice/platform/platform-integration-guide',
                        'freshservice/platform/platform-troubleshooting-guide',
                        {
                            type: 'category',
                            label: '📊 분석 및 리포팅',
                            collapsed: true,
                            items: [
                                {
                                    type: 'category',
                                    label: '📈 Analytics',
                                    collapsed: true,
                                    items: [
                                        'freshservice/platform/analytics/understanding-the-service-desk-at-a-glance-report',
                                        'freshservice/platform/analytics/analytics-data-warehouse-and-etl-processes',
                                        'freshservice/platform/analytics/common-reports-using-analytics',
                                        'freshservice/platform/analytics/comparing-multiple-metrics-in-a-widget',
                                        'freshservice/platform/analytics/custom-metrics-and-custom-attributes',
                                        'freshservice/platform/analytics/exporting-data-from-analytics-to-power-bi',
                                        'freshservice/platform/analytics/exporting-data-from-analytics-to-tableau',
                                        'freshservice/platform/analytics/gain-visibility-into-service-operations-with-generative-ai-powered-freddy-insights',
                                        'freshservice/platform/analytics/generate-intuitive-reports-using-analytics-pro',
                                        'freshservice/platform/analytics/how-is-the-row-count-in-the-underlying-data-more-than-total-metrics-count-on-the-report-chart',
                                        'freshservice/platform/analytics/incremental-data-exports-in-freshservice',
                                        'freshservice/platform/analytics/reporting-on-approval-metrics-in-analytics',
                                        'freshservice/platform/analytics/setting-up-time-sheet-reports',
                                        'freshservice/platform/analytics/understanding-sorting-behaviour-in-freshservice-analytics',
                                        'freshservice/platform/analytics/why-are-field-values-not-loading-in-analytics-filters',
                                    ],
                                },
                                {
                                    type: 'category',
                                    label: '📋 Reporting',
                                    collapsed: true,
                                    items: [
                                        'freshservice/platform/reporting/asset-reports',
                                        'freshservice/platform/reporting/change-reports',
                                        'freshservice/platform/reporting/the-advanced-reporting-suite',
                                        'freshservice/platform/reporting/the-enterprise-reporting-suite',
                                        'freshservice/platform/reporting/understanding-the-helpdesk-at-a-glance-report',
                                    ],
                                },
                            ],
                        },
                        {
                            type: 'category',
                            label: '🛠️ 자동화 및 워크플로우',
                            collapsed: true,
                            items: [
                                {
                                    type: 'category',
                                    label: '⚡ Workflow Automator',
                                    collapsed: true,
                                    items: [
                                        'freshservice/platform/workflow-automator/advanced-workflow-trigger-configuration',
                                        'freshservice/platform/workflow-automator/auto-assigning-tickets-to-agents-in-a-group-round-robin',
                                        'freshservice/platform/workflow-automator/expression-builder-node-troubleshooting-guide',
                                        'freshservice/platform/workflow-automator/fix-for-custom-objects-behavior-in-workflow-automator',
                                        'freshservice/platform/workflow-automator/introduction-to-scheduled-workflows',
                                        'freshservice/platform/workflow-automator/json-parser-node',
                                        'freshservice/platform/workflow-automator/operators-in-expression-builder-node',
                                        'freshservice/platform/workflow-automator/powerful-placeholders-with-liquid-filters',
                                        'freshservice/platform/workflow-automator/reader-node',
                                        'freshservice/platform/workflow-automator/sample-usecase-invoke-webrequest-node-to-fetch-ticket-details-and-perform-actions-based-on-it',
                                        'freshservice/platform/workflow-automator/scheduled-workflows-for-software-applications-and-users',
                                        'freshservice/platform/workflow-automator/web-request-node',
                                    ],
                                },
                            ],
                        },
                        {
                            type: 'category',
                            label: '🎯 사용자 정의 객체',
                            collapsed: true,
                            items: [
                                'freshservice/platform/custom-objects/creating-custom-objects',
                                'freshservice/platform/custom-objects/importing-and-exporting-custom-objects',
                                'freshservice/platform/custom-objects/using-custom-objects-in-workflows',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🏢 Freshworks Organization',
                            collapsed: true,
                            items: [
                                'freshservice/platform/freshworks-organization/introducing-freshworks-organization',
                                'freshservice/platform/freshworks-organization/migrating-freshservice-sso-to-freshworks-organization',
                                'freshservice/platform/freshworks-organization/setting-up-sso-policies-in-freshworks-organization',
                                'freshservice/platform/freshworks-organization/upgrading-multi-account-configurations-to-freshworks-organization',
                                'freshservice/platform/freshworks-organization/upgrading-msp-mode-accounts-to-freshworks-organization',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🔐 보안 및 인증',
                            collapsed: true,
                            items: [
                                'freshservice/platform/credential-store/centralized-credential-store',
                            ],
                        },
                        {
                            type: 'category',
                            label: '💼 구독 관리',
                            collapsed: true,
                            items: [
                                'freshservice/platform/managing-freshservice-subscription/how-to-manage-a-freshservice-subscription-during-trial',
                                'freshservice/platform/managing-freshservice-subscription/faqs',
                            ],
                        },
                        {
                            type: 'category',
                            label: '🔄 API 및 마이그레이션',
                            collapsed: true,
                            items: [
                                'freshservice/platform/api-v1-deprecation/deprecating-v1-apis-for-freshservice',
                            ],
                        },
                    ],
                },
            ],
        },
    ],
};
exports.default = sidebars;
