import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // 시작하기 페이지를 맨 위에 배치
    'intro',

    // Freshservice - IT 서비스 관리
    {
      type: 'category',
      label: '🔧 Freshservice (ITSM)',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '🧪 PoC 가이드',
          collapsed: true,
          items: [
            'freshservice/poc/guide',
          ],
        },
        {
          type: 'category',
          label: '📚시작하기',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: '👥 사용자 관리',
              collapsed: true,
              items: [
                'freshservice/start/users/agents',
                'freshservice/start/users/roles-permissions',
                'freshservice/start/users/requesters',
                'freshservice/start/users/import-csv',
                'freshservice/start/users/agent-id',
                'freshservice/start/users/custom-fields',
                'freshservice/start/users/csv-guidelines',
                'freshservice/start/users/merge-requesters',
                'freshservice/start/users/password-policy',
                'freshservice/start/users/change-password',
                'freshservice/start/users/department-fields',
                'freshservice/start/users/export-agents',
                'freshservice/start/users/import-agents',
                'freshservice/start/users/auto-associate',
                'freshservice/start/users/group-members',
                'freshservice/start/users/agent-groups',
                'freshservice/start/users/requester-groups',
                'freshservice/start/users/manage-requesters',
                'freshservice/start/users/import-departments',
                'freshservice/start/users/merge-advanced',
              ],
            },
            {
              type: 'category',
              label: '🌐 셀프 서비스 포털',
              collapsed: true,
              items: [
                'freshservice/start/portal/branding',
                'freshservice/start/portal/vanity-url',
                'freshservice/start/portal/access-login',
                'freshservice/start/portal/ssl-cert',
                'freshservice/start/portal/chatbot',
              ],
            },
            {
              type: 'category',
              label: '⚙️ 시스템 설정',
              collapsed: true,
              items: [
                'freshservice/start/setup/onboarding',
                'freshservice/start/setup/requirements',
                'freshservice/start/setup/mailbox',
                'freshservice/start/setup/agents',
                'freshservice/start/setup/asset-scan',
                'freshservice/start/setup/timezones',
                'freshservice/start/setup/languages',
                'freshservice/start/setup/catalog',
                'freshservice/start/setup/sla-policy',
              ],
            },
            {
              type: 'category',
              label: '📝 폼 및 템플릿',
              collapsed: true,
              items: [
                'freshservice/start/forms/field-types',
                'freshservice/start/forms/setup-fields',
                'freshservice/start/forms/custom-fields',
                'freshservice/start/forms/dependent-fields',
                'freshservice/start/forms/using-dependent',
                'freshservice/start/forms/dropdown',
                'freshservice/start/forms/multi-select',
                'freshservice/start/forms/rich-text',
                'freshservice/start/forms/dynamic-sections',
                'freshservice/start/forms/archive-fields',
                'freshservice/start/forms/ticket-template',
                'freshservice/start/forms/dynamic-forms',
                'freshservice/start/forms/change-forms',
                'freshservice/start/forms/business-rules',
                'freshservice/start/forms/troubleshooting',
                'freshservice/start/forms/desk-statuses',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '👨‍💼 관리자 가이드',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: '⚙️ 관리자 설정',
              collapsed: true,
              items: [
                'freshservice/admin/settings/index',
                'freshservice/admin/settings/general',
                'freshservice/admin/settings/users',
                'freshservice/admin/settings/productivity',
                'freshservice/admin/settings/reorganization',
                'freshservice/admin/settings/assets',
                'freshservice/admin/settings/export-data',
              ],
            },
            {
              type: 'category',
              label: '🎯 시작하기',
              collapsed: true,
              items: [
                'freshservice/admin/start/index',
              ],
            },
            {
              type: 'category',
              label: '📊 CMDB',
              collapsed: true,
              items: [
                'freshservice/admin/cmdb/index',
              ],
            },
            {
              type: 'category',
              label: '🚀 릴리스 관리',
              collapsed: true,
              items: [
                'freshservice/admin/release/index',
              ],
            },
            {
              type: 'category',
              label: '💡 솔루션 (지식 베이스)',
              collapsed: true,
              items: [
                'freshservice/admin/solutions/index',
              ],
            },
            {
              type: 'category',
              label: '🔄 변경 관리',
              collapsed: true,
              items: [
                'freshservice/admin/change/index',
              ],
            },
            {
              type: 'category',
              label: '📋 인시던트 관리',
              collapsed: true,
              items: [
                'freshservice/admin/incident/index',
              ],
            },
            {
              type: 'category',
              label: '🔍 문제 관리',
              collapsed: true,
              items: [
                'freshservice/admin/problem/index',
              ],
            },
            {
              type: 'category',
              label: '📈 보고서',
              collapsed: true,
              items: [
                'freshservice/admin/reports/index',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '📘 IT 서비스 관리 지원 가이드',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: '🎫 티켓 시작하기',
              collapsed: true,
              items: [
                'freshservice/itsm/tickets/view-access',
                'freshservice/itsm/tickets/views',
                'freshservice/itsm/tickets/filtering',
                'freshservice/itsm/tickets/kanban',
                'freshservice/itsm/tickets/properties',
                'freshservice/itsm/tickets/statuses',
                'freshservice/itsm/tickets/merge',
                'freshservice/itsm/tickets/walk-in',
                'freshservice/itsm/tickets/canned-responses',
                'freshservice/itsm/tickets/placeholders',
                'freshservice/itsm/tickets/freddy-suggestions',
                'freshservice/itsm/tickets/kbase-solutions',
                'freshservice/itsm/tickets/private-notes',
                'freshservice/itsm/tickets/public-notes',
                'freshservice/itsm/tickets/collision-detect',
                'freshservice/itsm/tickets/dashboards',
                'freshservice/itsm/tickets/list-view',
                'freshservice/itsm/tickets/table-refresh',
                'freshservice/itsm/tickets/auto-refresh',
                'freshservice/itsm/tickets/navigation',
                'freshservice/itsm/tickets/trend-widgets',
                'freshservice/itsm/tickets/troubleshoot',
                'freshservice/itsm/tickets/canned-deprecation',
              ],
            },
            {
              type: 'category',
              label: '📋 인시던트 관리',
              collapsed: true,
              items: [
                'freshservice/itsm/incident/sla-policies',
                'freshservice/itsm/incident/default-sla',
                'freshservice/itsm/incident/multiple-sla',
                'freshservice/itsm/incident/business-hours',
                'freshservice/itsm/incident/multiple-hours',
                'freshservice/itsm/incident/priority-matrix',
                'freshservice/itsm/incident/escalations',
                'freshservice/itsm/incident/feedback',
                'freshservice/itsm/incident/field-manager',
                'freshservice/itsm/incident/support-email',
                'freshservice/itsm/incident/spf-record',
              ],
            },
            {
              type: 'category',
              label: '🔄 변경 관리',
              collapsed: true,
              items: [
                'freshservice/itsm/change/getting-started',
                'freshservice/itsm/change/phases',
                'freshservice/itsm/change/planning-tasks',
                'freshservice/itsm/change/types',
                'freshservice/itsm/change/workflows',
                'freshservice/itsm/change/templates',
                'freshservice/itsm/change/request-agent',
                'freshservice/itsm/change/enablement',
                'freshservice/itsm/change/advisory-board',
                'freshservice/itsm/change/agent-roles',
                'freshservice/itsm/change/ola-policies',
              ],
            },
            {
              type: 'category',
              label: '🎯 티켓 액션',
              collapsed: true,
              items: [
                'freshservice/itsm/actions/time-entries',
                'freshservice/itsm/actions/custom-time-fields',
                'freshservice/itsm/actions/activity-history',
                'freshservice/itsm/actions/child-tickets',
                'freshservice/itsm/actions/child-incidents',
                'freshservice/itsm/actions/link-problems',
                'freshservice/itsm/actions/link-changes',
                'freshservice/itsm/actions/share-agents',
                'freshservice/itsm/actions/share-requesters',
                'freshservice/itsm/actions/forward-tickets',
                'freshservice/itsm/actions/watcher',
                'freshservice/itsm/actions/canned-responses',
                'freshservice/itsm/actions/solution-response',
                'freshservice/itsm/actions/satisfaction-survey',
                'freshservice/itsm/actions/closure-rules',
                'freshservice/itsm/actions/keyboard-shortcuts',
                'freshservice/itsm/actions/email-commands',
                'freshservice/itsm/actions/export-tickets',
                'freshservice/itsm/actions/archival',
                'freshservice/itsm/actions/email-not-converted',
                'freshservice/itsm/actions/email-bot',
                'freshservice/itsm/actions/team-huddle-end',
              ],
            },
            {
              type: 'category',
              label: '🤖 티켓 자동화',
              collapsed: true,
              items: [
                'freshservice/itsm/automation/supervisor-rules',
                'freshservice/itsm/automation/supervisor-config',
                'freshservice/itsm/automation/scenario-create',
                'freshservice/itsm/automation/scenario-execute',
                'freshservice/itsm/automation/recurring-scheduler',
              ],
            },
            {
              type: 'category',
              label: '🤖 Freddy AI 에이전트',
              collapsed: true,
              items: [
                'freshservice/itsm/freddy-agent/slack-setup',
                'freshservice/itsm/freddy-agent/teams-setup',
                'freshservice/itsm/freddy-agent/ticket-context',
                'freshservice/itsm/freddy-agent/teams-faqs',
                'freshservice/itsm/freddy-agent/teams-upgrade',
              ],
            },
            {
              type: 'category',
              label: '🧠 Freddy AI 코파일럿',
              collapsed: true,
              items: [
                'freshservice/itsm/freddy-copilot/unlock-productivity',
                'freshservice/itsm/freddy-copilot/reply-suggestions',
                'freshservice/itsm/freddy-copilot/ticket-summary',
                'freshservice/itsm/freddy-copilot/quick-actions',
                'freshservice/itsm/freddy-copilot/help-articles',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '🏗️ IT 자산 관리 (ITAM)',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: '🚀 자산 관리 시작하기',
              collapsed: true,
              items: [
                'freshservice/itam/start/index',
                'freshservice/itam/start/asset-types',
                'freshservice/itam/start/depreciation',
                'freshservice/itam/start/add-asset',
                'freshservice/itam/start/import-assets',
                'freshservice/itam/start/view-info',
                'freshservice/itam/start/bulk-update',
                'freshservice/itam/start/customize-columns',
                'freshservice/itam/start/asset-states',
                'freshservice/itam/start/assign-assets',
                'freshservice/itam/start/mobile-scanning',
                'freshservice/itam/start/impact-evaluation',
                'freshservice/itam/start/barcode-labels',
                'freshservice/itam/start/create-incidents',
                'freshservice/itam/start/import-locations',
                'freshservice/itam/start/assignment-history',
                'freshservice/itam/start/activity-reporting',
                'freshservice/itam/start/field-limitations',
                'freshservice/itam/start/conditional-fields',
                'freshservice/itam/start/d42-mapping',
                'freshservice/itam/start/cloud-deprecation',
                'freshservice/itam/start/itam-switching',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '❓ FAQ',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'freshservice/faqs/agents/index',
              label: '에이전트 및 그룹',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/analytics/index',
              label: '분석 및 리포트',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/announcements/index',
              label: '공지사항',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/api/index',
              label: 'API & Webhooks',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/assets/index',
              label: '자산 관리',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/automation/index',
              label: '자동화 및 트리거',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/sla/index',
              label: '업무 시간 및 SLA',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/change/index',
              label: '변경 관리',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/email/index',
              label: '이메일',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/notifications/index',
              label: '이메일 알림',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/feedback/index',
              label: '피드백 위젯',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/incidents/index',
              label: '인시던트 및 서비스 요청',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/projects/index',
              label: 'New-Gen 프로젝트 관리',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/orchestration/index',
              label: '오케스트레이션',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/pricing/index',
              label: '가격 정책',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/priority/index',
              label: '우선순위 매트릭스',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/problems/index',
              label: '문제 관리',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/release/index',
              label: '릴리스 관리',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/reports/index',
              label: '보고서',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/sandbox/index',
              label: '샌드박스',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/catalog/index',
              label: '서비스 카탈로그',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/desk/index',
              label: '서비스 데스크 FAQ',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/sso/index',
              label: 'SSO 및 인증',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/tasks/index',
              label: '작업 관리',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/workflow/index',
              label: '티켓팅 워크플로우',
            },
            {
              type: 'doc',
              id: 'freshservice/faqs/workspaces/index',
              label: '워크스페이스',
            },
          ],
        },
        {
          type: 'category',
          label: '🔧 플랫폼',
          collapsed: true,
          items: [
            'freshservice/platform/overview',
            'freshservice/platform/integration',
            'freshservice/platform/troubleshooting',
            {
              type: 'category',
              label: '📊 분석 및 리포팅',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: '📈 Analytics',
                  collapsed: true,
                  items: [
                    'freshservice/platform/analytics/desk-glance',
                    'freshservice/platform/analytics/data-warehouse',
                    'freshservice/platform/analytics/common-reports',
                    'freshservice/platform/analytics/compare-metrics',
                    'freshservice/platform/analytics/custom-metrics',
                    'freshservice/platform/analytics/power-bi',
                    'freshservice/platform/analytics/tableau',
                    'freshservice/platform/analytics/freddy-insights',
                    'freshservice/platform/analytics/analytics-pro',
                    'freshservice/platform/analytics/row-count-issue',
                    'freshservice/platform/analytics/incremental-export',
                    'freshservice/platform/analytics/approval-metrics',
                    'freshservice/platform/analytics/timesheet-reports',
                    'freshservice/platform/analytics/sorting-behavior',
                    'freshservice/platform/analytics/filter-loading',
                  ],
                },
                {
                  type: 'category',
                  label: '📋 Reporting',
                  collapsed: true,
                  items: [
                    'freshservice/platform/reporting/asset-reports',
                    'freshservice/platform/reporting/change-reports',
                    'freshservice/platform/reporting/advanced-suite',
                    'freshservice/platform/reporting/enterprise-suite',
                    'freshservice/platform/reporting/helpdesk-glance',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: '🛠️ 자동화 및 워크플로우',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: '⚡ Workflow Automator',
                  collapsed: true,
                  items: [
                    'freshservice/platform/workflow/trigger-config',
                    'freshservice/platform/workflow/round-robin',
                    'freshservice/platform/workflow/expression-troubleshoot',
                    'freshservice/platform/workflow/custom-objects-fix',
                    'freshservice/platform/workflow/scheduled-intro',
                    'freshservice/platform/workflow/json-parser',
                    'freshservice/platform/workflow/expression-operators',
                    'freshservice/platform/workflow/liquid-filters',
                    'freshservice/platform/workflow/reader-node',
                    'freshservice/platform/workflow/webrequest-sample',
                    'freshservice/platform/workflow/scheduled-software',
                    'freshservice/platform/workflow/webrequest-node',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: '🎯 사용자 정의 객체',
              collapsed: true,
              items: [
                'freshservice/platform/objects/create',
                'freshservice/platform/objects/import-export',
                'freshservice/platform/objects/workflows',
              ],
            },
            {
              type: 'category',
              label: '🏢 Freshworks Organization',
              collapsed: true,
              items: [
                'freshservice/platform/org/introduction',
                'freshservice/platform/org/migrate-sso',
                'freshservice/platform/org/sso-policies',
                'freshservice/platform/org/multi-account',
                'freshservice/platform/org/msp-upgrade',
              ],
            },
            {
              type: 'category',
              label: '🔐 보안 및 인증',
              collapsed: true,
              items: [
                'freshservice/platform/security/credential-store',
              ],
            },
            {
              type: 'category',
              label: '💼 구독 관리',
              collapsed: true,
              items: [
                'freshservice/platform/subscription/trial-manage',
                'freshservice/platform/subscription/faqs',
              ],
            },
            {
              type: 'category',
              label: '🔄 API 및 마이그레이션',
              collapsed: true,
              items: [
                'freshservice/platform/api/v1-deprecation',
              ],
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
